remote_theme: pmarsceill/just-the-docs
title: OnePoint Global API 
description: The OnePoint Global API Documentation
url: "https://onepointglobal.github.io/OnePoint-API-Documentation-V2" 

color_scheme: default

# Enable or disable heading anchors
heading_anchors: true
